
#Get rooms
# @name getRooms
@baseUrl = http://localhost:3000
GET {{baseUrl}}/rooms

###

# Create Room
# @name createRoom
POST {{baseUrl}}/rooms 
Accept: application/json
Content-Type: application/json

{
    "name": "Sala de teste",
    "description": "A room for testing purposes"
}

###

@roomId = {{createRoom.response.body.$.roomId}}
###
# Get room questions
GET {{baseUrl}}/rooms/{{roomId}}/questions

###
# Create a new question
POST {{baseUrl}}/rooms/{{roomId}}/questions
Content-Type: application/json

{
  "question": "Qual a melhor forma de aprender NodeJS?"
}

###
# Health Check
GET {{baseUrl}}/health


